return {
  -- {
  --   "williamboman/mason.nvim",
  --   opts = function(_, opts)
  --     vim.list_extend(opts.ensure_installed, {
  --       "debugpy",
  --       "pyright",
  --       "ruff",
  --       "ruff-lsp",
  --     })
  --   end,
  -- },
  -- {
  --   "stevearc/conform.nvim",
  --   opts = {
  --     formatters_by_ft = {
  --       python = { "ruff_fix", "ruff_format" },
  --     },
  --   },
  -- },
}
